[package]
name = "python-rust-example"
version = "0.1.0"
authors = ["Daniele Esposti <daniele.esposti@corp.badoo.com>"]
edition = "2018"

[lib]
name = "example"
crate-type = ["dylib"]

[dependencies]
cpython = "*"
